export const dialog = {
	text: [
		'Oops. . .  Looks like you are lost.',
		"Now that you're here, want to try out your golf skills?",
	],
	buttons: [
		{
			href: '#',
			onClick: 'close', // something truthy
			text: "Yeah! let's go!",
		},
		{
			href: '/',
			text: 'No, go back.',
		},
	],
}

// Todo: Censor?

export const arrSwearWords_orig = [
	'shit',
	'fuck',
	'cock',
	'ass',
	'asshole',
	'bastard',
	'bitch',
	'bloody',
	'bollocks',
	'Christ on a bike',
	'Christ on a cracker',
	'crap',
	'cunt',
	'damn it',
	'Jesus',
	'Jesus Christ',
	'Jesus, Mary and Joseph',
	'motherfucker',
	'mother fuck',
	'son of a bitch',
	'son of a gun',
	'sweet Jesus',
	'sweet baby Jesus',
	'arse',
	'arsehole',
	'ass-pirate',
	'ass-jabber',
	'ass-bandit',
	'cocknugget',
	'dick',
	'dickwad',
	'dickhead',
	'jackass',
	'nuts',
	'nutsack',
	'pussy',
	'shitbag',
	'thundercunt',
	'tit',
	'twat',
	'wanker',
	'Holy mother',
	"Pete's sake",
	'Son of a gun',
	'Son of a biscuit eater',
	'mothertrucker',
	'fucktrumpet',
	'knobhead',
	'pissflaps',
	'dickweed',
	'arsebadger',
	'twatwaffle',
	'bellend',
	'pisswizard',
	'dickweasel',
	'tosser',
	'tosspot',
	'shit magnet',
	'shite',
	'bugger',
	'dickcheese',
	'butt muncher',
	'arsegoblin',
	'douchenozzle',
	'cunt muffin',
]
